spring.application.name=ProjetoFinalArqObj
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.h2.console.enabled=false
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/docs/api-docs
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.root=WARN
logging.level.com.example.ProjetoFinalArqObj=INFO
server.servlet.context-path=/
server.compression.enabled=true
server.compression.min-response-size=1024
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=when-authorized
server.port=8443
server.ssl.key-store-type=PKCS12
server.ssl.enabled=false
